### ISSUE TITLE
Please review my PR #5

### ISSUE THREAD

**Issue by hemangjoshi37a** [orbitdb/py-orbit-db-http-client#6]
Please review my PR #5

**Comment by hemangjoshi37a** [comment]
@phillmac bro would you now give me write access to this repo? Because I am really interested in this and I want to develop onto this but to do this I need to make sure that I am relavant to this project and my commits are merged and published as fast as they can because if not then the time I invested developing onto this library has much less outcome then otherwise it should be.

**Comment by phillmac** [comment]
I haven't been able to get approval for the write access, I am however entirely happy to keep reviewing PRs as time permits.
If my response time is causing too much of an issue I'm happy to review larger PRs too so you can work at your own speed and then merge the forks later.
